server.port=8004

spring.application.name=distribution-backend

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.com.distribution=DEBUG
